allprojects {
    group = 'comz'
    version = '1.0'
}

subprojects {
    apply plugin: 'java'

    sourceCompatibility = targetCompatibility = JavaLanguageVersion.of(21)

    repositories {
        mavenLocal()
    }
}

tasks.withType(JavaCompile).configureEach {
    //Ignore Java 8 warnings. Not much I can do here
    options.compilerArgs += ['-Xlint:deprecation']
}