import org.apache.tools.ant.filters.ReplaceTokens

apply plugin: 'idea'
apply plugin: 'maven-publish'

archivesBaseName = "comzombies-Universal"

repositories {
    mavenCentral()
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url 'https://oss.sonatype.org/content/repositories/central' }
    maven { url 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation project(':API')
    implementation project(':Compat')
    compileOnly "com.github.MilkBowl:VaultAPI:1.7.1"
    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
    implementation group: 'org.spigotmc', name: 'spigot-api', version: '26.3-R0.1-SNAPSHOT'
    implementation 'me.clip:placeholderapi:2.11.6'
}

jar {
    from project(":API").sourceSets.main.output.classesDirs
    from project(":Compat").sourceSets.main.output.classesDirs
}

processResources {
    from(sourceSets.main.resources.srcDirs) {
        filter ReplaceTokens, tokens: [
                "version": project.version.toString()
        ]
        duplicatesStrategy = 'INCLUDE'
    }
}

